### ISSUE TITLE
Results arrays

### ISSUE THREAD

**Issue by jg-rp** [mesarth/JSONPath-JS-Engine-Compliance#1]
Hi @mesarth,

Have you seen that the CTS schema was changed recently to allow a `results` array (of arrays) instead of a single `result` per test case?

For example, “basic, wildcard shorthand, object data” has an array of valid results because - according to RFC 9535 - values from JSON objects can be visited in any order.

**Comment by mesarth** [comment]
Hi @jg-rp,

Totally missed this change in the CTS schema, thanks for the heads up! Will adapt my script.

By the way, fantastic job on json-p3!
